Bounties-Network/BountiesAPI

- bounties_api/.coveragerc
- bounties_api/bounties/settings.py
- bounties_api/std_bounties/tests.py
- contract_subscriber/package-lock.json
- contract_subscriber/package.json
- contract_subscriber/test/test.js
```$ docker-compose exec bounties_api python manage.py test```
```$ docker-compose exec contract_subscriber npm run test```
Resolve #22
> Add support to code coverage for django and nodejs

- bounties_api/std_bounties/serializers.py
- bounties_api/user/management/commands/user_github_fields.py
@villanuevawill @codeluggage I needed the bounty stage to determine if a fulfillment should show pending acceptance or rejected (shows rejected if the bounty is in completed stage). Also figured I would add in the calculated_fulfillmentAmount so I didn't need to calculate it on the client.
> Updated fulfillment serializer

- bounties_api/std_bounties/urls.py
- bounties_api/std_bounties/views.py
@villanuevawill @codeluggage pretty simple PR. Just switch the comments over to the `ListModelMixin` so that we would get `count`, `results`, etc from the request instead of just an array.
> Comments endpoint refactored to use model mixins for viewsets

- bounties_api/std_bounties/client_helpers.py
@villanuevawill @codeluggage pulled off the number of revisions from the ipfs data and plopped it into the db. I'm defaulting to `None` so it won't show any revisions on the frontend for older bounties, but newer ones will have the revisions listed on their bounty page. Let me know if y'all have a better default. Cheers
> Add revisions data to bounty

- bounties_api/notifications/email.py
- bounties_api/notifications/notification_client.py
- bounties_api/notifications/templates/completedBounty.html
Use description from fulfillment instead of bounty for email template. Several of these references have been missing, and it's looking messier and messier. A refactor and more functional approach would possibly make this cleaner.
> Fix fulfilment description

- bounties_api/std_bounties/views.py
@villanuevawill @codeluggage needed to add this so i can order the submissions on the whitelabel from newest to oldest
> added ordering filter to fulfillments endpoint

- bounties_api/notifications/email.py
- bounties_api/notifications/notification_client.py
- bounties_api/notifications/templates/fulfillmentUpdated.html
- bounties_api/notifications/templates/submissionAccepted.html
Fix misconception about which descriptions were meant to send with emails, only use fulfillment descriptions and avoid the bounty description completely.
In essence this means that we never send a bounty description by email notification, only the description coming from the event itself.
> Fix email description switcheroo

- bounties_api/user/management/commands/user_github_fields.py
@villanuevawill @codeluggage only load github profile image if the user has no existing profile image
> Only load github profile image if the user has no existing profile image

- bounties_api/notifications/templates/commentOnBounty.html
Now that more users than just the issuer receive a notification when a comment has been posted on a bounty they're involved with, we want that to reflect in the copy.
> Copy change to make comment notification user agnostic

- bounties_api/notifications/email.py
- bounties_api/std_bounties/management/commands/bounties_subscriber.py
- Use the `bounty.platform` in the profile links
- Print better in bounties_subscriber
> Fix platform in email links

- bounties_api/std_bounties/filters.py
For some reason, there was no filter on the draft endpoint for the issuer so I was seeing other people's drafts. This fixes that issue.
> Add issuer filter to drafts endpoint

- bounties_api/bounties/utils.py
- bounties_api/notifications/email.py
- bounties_api/notifications/notification_client.py
- Switch to using a function
- Quantize first, then normalize
- Set precision for usd and tokens, but use quantize for the final decimal points
> Correct decimal rounding for dollars and tokens

- bounties_api/std_bounties/views.py
@villanuevawill @codeluggage with a fresh set of eyes, I was able to simplify the logic in the query set for fulfillments a lot. There are really only 2 cases:
1. A user is logged in -- therefore the query set should return all fulfillments where they either the fulfiller, bounty owner, or the fulfillment is publicly visible.
2. A user is not logged in  -- should only return fulfillments that are set to public
> Simplify fulfillments query set by leaning on filters

- bounties_api/notifications/email.py
@villanuevawill without this check we'd query when we didn't need the count. With all these new emails, it is starting to get a little unwieldy. Any thoughts on splitting this?
> Fix remaining submissions reference in contribution email

- bounties_api/std_bounties/views.py
This is related to:
https://github.com/Bounties-Network/Explorer/pull/179
Draft bounties are now looked up by their UID or hash field. This keeps sharable links private.
Associated task:
- https://trello.com/c/OYQTFSWU/6-draft-links-should-be-open-but-should-just-be-based-on-the-uuid-hash-this-makes-it-sharable
> Lookup field is now uid

- bounties_api/notifications/email.py
- bounties_api/notifications/notification_client.py
- bounties_api/notifications/templates/receivedRating.html
@villanuevawill @c-o-l-o-r the rating emails were not being rendered with data, and needed to pull in the average calculation based on the sender and receiver of the rating. 
I also fixed colours in the email, and made deduplication more unique for ratings to guard against an edge case I ran into when testing rating email delivery. This makes the deduplication differ between issued and received. 
The rating is being rounded to 2 digits when it's not an exact number, in the text below the main email graphics. Not in the circle, just in the text.
> Fix average rating email

- bounties_api/std_bounties/client_helpers.py
@villanuevawill @codeluggage it looks like the logic to retrieve the `expiry_date` was never triggered because it failed the `if metadata.get('platform', '') is 'gitcoin'` check. To fix all affected bounties already in the system, please use the follow script:
```
from std_bounties.models import Bounty
from datetime import datetime
import json
bounties = Bounty.objects.all()
for bounty in bounties:
data_JSON = bounty.data_json
data = json.loads(data_JSON)
meta = data.get('meta', {})
if 'payload' in data:
data = data.get('payload')
if meta.get('platform', '') == 'gitcoin' and 'expire_date' in data:
bounty.deadline = datetime.utcfromtimestamp(int(data.get('expire_date', '')))
bounty.save()
```
> Fix Gitcoin bounties' deadlines

- bounties_api/notifications/notification_helpers.py
@villanuevawill @c-o-l-o-r 
Set it at the top as all the following code has no use without an email being set already. The field on the model is:
```
email = models.CharField(max_length=128, blank=True)
```
Skips sending an email when creating a new user, commenting on a bounty, and then someone else comments on the same bounty.
> Ignore emails for users that don't have an email set yet

- codecov.yml
- Adds `codecov.yml`
- Sets threshold to 2% to fail
> Less sensitive CodeCov

- bounties_api/notifications/templates/bountyExpired.html
- bounties_api/notifications/templates/bountyTransferReceived.html
- bounties_api/notifications/templates/bountyTransferSent.html
- bounties_api/notifications/templates/commentOnBounty.html
- bounties_api/notifications/templates/contributionReceived.html
- bounties_api/notifications/templates/fulfillmentSubmitted.html
- bounties_api/notifications/templates/fulfillmentUpdated.html
- bounties_api/notifications/templates/receivedRating.html
- bounties_api/notifications/templates/submissionAccepted.html
Trello: https://trello.com/c/wzNNbtQD
This makes sure that the USD price never line breaks, which is important for smaller mobile screens.
> Force no line break for USD price in emails

- bounties_api/notifications/templates/commentOnBounty.html
Trello: https://trello.com/c/wzNNbtQD
This was missing from the previous PR, I did not catch that there were 2 pictures in the Trello card.
> Avoid word break on the reply button for mobile

- .circleci/config.yml
- Credentials aren't always available, for example from forked PR's
- Without credentials, docker hub commands fail, and failures break the build
- Simply skip the docker hub login and image uploading, and avoid failing
> Only log in to docker hub and push images if credentials are available

- bounties_api/std_bounties/client_helpers.py
@codeluggage @c-o-l-o-r gitcoin fulfillments should default to public. All of their work is open and on github, so if someone opens a gitcoin bounty, they should be able to see the submissions.
> Gitcoin should never have private fulfillments

- bounties_api/notifications/notification_client.py
- bounties_api/notifications/notification_helpers.py
- bounties_api/utils/dashboard_notification_update.py
Trello: https://trello.com/c/iQLlep6Q
The dashboard notification for review issued was using the wrong profile URL. 
- New dashboard notifications now use the proper user for the issued dashboard notification
- The bounty ID was added to the UID of the notifications, making it easier to look them up in the future
- A one-of utility script was added to update past dashboard notifications
Plan for updating past notifications is: 
1. Deploy
1. Change the script on the server to comment out the `dash.save()` call, so it will actually save
1. Run the script, taking care to note the output of `GOT MULTIPLE BOUNTIES FOR TITLE:`
1. Manually edit the occurrences of the multiple title bounties where the link is wrong
1. Done! :)
> Always use receiver of review as URL target

- contract_subscriber/eventsRetriever.js
This skips over transactions that originate from another smart contract and logs them in rollbar so that we can potentially take manual action.
> hotfix: contract subscriber issue
