Bounties-Network/BountiesAPI

- .vscode/settings.json
- bounties_api/static/apischema.yaml
- bounties_api/std_bounties/urls.py
- bounties_api/std_bounties/views.py
Providing an endpoint that returns all tokens that have been used at least once in a contract. It should also return its associated token data. #5 
/token
> Token Endpoint

- README.md
just fixing the readme :smirk:
> Fixing the docker commands in readme

- bounties_api/std_bounties/views.py
> Updated search to include issuer address

- bounties_api/std_bounties/client_helpers.py
> Syntax fix

- bounties_api/std_bounties/client_helpers.py
Fixed issue due to web3 update on returning bytestrings.
> Web3 bug - Fixed bug where now a bytestring is returned

- bounties_api/bounties/tests.py
- bounties_api/std_bounties/tests.py
As in title, tests for `bounty_url_for` are moved to other module
> Move test for bounty_url_for to different module and adjust other tests

- bounties_api/requirements.txt
- bounties_api/std_bounties/client_helpers.py
> Updated for poa middleware

- bounties_api/std_bounties/client_helpers.py
> Add consensysrinkeby to the list for POA.

- bounties_api/bounties/settings.py
> Should send environment properly

- bounties_api/std_bounties/filters.py
> Add experiencelevel filter.

- bounties_api/static/apischema.yaml
I will probably squash all these commits into one when I finish.
> Swagger update

- bounties_api/static/apischema.yaml
- bounties_api/std_bounties/views.py
> Added count to leaderboard endpoints and updated swagger

- bounties_api/std_bounties/client_helpers.py
- bounties_api/std_bounties/serializers.py
- bounties_api/std_bounties/views.py
> Minor updates to make bounty creation, etc. compatible.

- bounties_api/std_bounties/client_helpers.py
- bounties_api/user/models.py
- bounties_api/user/serializers.py
- bounties_api/user/user_urls.py
- bounties_api/user/views.py
> Skills endpoint

- bounties_api/std_bounties/client_helpers.py
> Temp hotfix on delayed ipfs calls

- sql_jobs/hourly/skill_ranks.sql
> Skill ranks query added.

- bounties_api/std_bounties/bounty_client.py
FYI - @codeluggage @c-o-l-o-r  this fixed things :)
> objects not obects :)

- bounties_api/std_bounties/client_helpers.py
> :) - production error.

- bounties_api/std_bounties/models.py
> Users sholdn't be automatically named.

- bounties_api/analytics/filters.py
- bounties_api/analytics/management/commands/timeline_generator.py
- bounties_api/analytics/migrations/0001_squashed_0006_auto_20180504_0536.py
- bounties_api/analytics/models.py
- bounties_api/analytics/serializers.py
- bounties_api/analytics/tests.py
- bounties_api/analytics/views.py
added support for bounty categories
added support for tokens on our platform
migrate from `schema` to `platform`
> Bounty categories and token analytics feature

- bounties_api/std_bounties/management/commands/bounties_subscriber.py
The old blacklisted keys were conflicting, and we need to keep the permanently (corrupted events, etc.) and temporarily blacklisted events separate.
- Added a new key reference to `pending_blacklist`
- Kept old key for `blacklist` the same
- Always skip events for `blacklist`
- Add events to list for `pending_blacklist`, like normal
> Split redis blacklisting into permanent and pending

- bounties_api/std_bounties/filters.py
- bounties_api/std_bounties/urls.py
- bounties_api/std_bounties/views.py
> Reviews endpoint for user

- bounties_api/bounties/tests.py
- bounties_api/bounties/utils.py
> update links in notifictions

- bounties_api/std_bounties/management/commands/bounties_subscriber.py
> Update issue review link

- bounties_api/user/views.py
> empty platform returns all

- bounties_api/std_bounties/management/commands/bounties_subscriber.py
I was deleting both in `handle_message` and when the event failed, which made it so retrying tried to double delete.
> Stop double delete of SQS events

- bounties_api/std_bounties/fixtures/languages.csv
> Fix languages fixture

- bounties_api/std_bounties/management/commands/bounties_subscriber.py
Check against the message_deduplication_id and continue if it has been set. This should have been part of the code a long time ago!
> Use message_deduplication_id

- bounties_api/std_bounties/management/commands/bounties_subscriber.py
Hotfix for not checking if value exists first.
> Another redis check for deduplication

- bounties_api/std_bounties/management/commands/bounties_subscriber.py
Quick fix for multiple messages from sqs
> Remove SQS message from queue when deduplication ID is found

- bounties_api/notifications/notification_client.py
- bounties_api/notifications/notification_helpers.py
- bounties_api/notifications/views.py
- bounties_api/std_bounties/client_helpers.py
- bounties_api/std_bounties/models.py
This PR - adds the actual event date from the contract to the notification model. This lets us give the true time of occurrence on the dashboard.
Other miscellaneous fixes (User names/emails updated based on bounty, etc.) and proper tracking of saved user.
> Msc fixes and event dates added to notifications.

- contract_subscriber/index.js
- contract_subscriber/web3_config.js
Intermittent erroring from infura due to geth node issues on latest block.
> Geth ERRORING

- bounties_api/notifications/notification_client.py
This will fix looping over comments to notify all commenters.
> Fix iteration for comments on the bounty

- bounties_api/notifications/email.py
- bounties_api/notifications/notification_client.py
The comment was not being passed along and replaced with the rest of the text
> Fix missing comment in email template

- bounties_api/notifications/notification_client.py
- bounties_api/std_bounties/serializers.py
After discussing this internally, we came to the conclusion to remove the draft notifications for now and revisit after launch.
> Rip out draft notifications

- bounties_api/notifications/notification_client.py
- bounties_api/std_bounties/views.py
Fixes review UID reference - https://rollbar.com/villanuevawill/Bounties/items/297/
> Fixes review UID reference

- bounties_api/notifications/notification_client.py
The user from the loop was not being used for the email target, causing the commenter emailing issue.
> Fix commenter emails

- bounties_api/notifications/templates/completedBounty.html
This also fixes some `<br>` references.
> Stop using the same profile image for both users in emails

- bounties_api/notifications/email.py
- bounties_api/notifications/templates/receivedRating.html
Adjust colors according to front end for rating emails. Ideally a color guide can be shared between projects in the future, but for now I'm marking them with comments and using the HEX directly.
> Rating email colors

- sql_jobs/hourly/category_ranks_beeess.sql
- sql_jobs/hourly/category_ranks_berlin.sql
> Added category scripts for berlin and beesss

- bounties_api/notifications/notification_client.py
- bounties_api/notifications/notification_templates.py
- The same sentences were used to describe both
- The string_data for ContributionReceived was missing
> Change string_data for ContributionAdded and ContributionReceived

- bounties_api/std_bounties/management/commands/bounties_subscriber.py
- bounties_api/std_bounties/message.py
- bounties_api/std_bounties/tests.py
- Merges in the code from `master` and modify it to work with the current `bounties_subscriber.py` code
- Applies the hotfix we recently did (do we still need this hotfix now @villanuevawill ?)
- Cleans up some pep8
> 504 blacklisting added to whitelabel

- bounties_api/notifications/email.py
> Fix review email link

- bounties_api/notifications/notification_client.py
Add fulfillers to the list of users to notify when a comment is received
> Notify fulfillers on comment received

- bounties_api/analytics/filters.py
- bounties_api/analytics/management/commands/fake_timeline.py
- bounties_api/analytics/serializers.py
- bounties_api/analytics/views.py
- bounties_api/bounties/urls.py
- bounties_api/bounties/utils.py
- bounties_api/bounties/wsgi.py
- bounties_api/manage.py
- bounties_api/notifications/models.py
- bounties_api/std_bounties/client_helpers.py
- bounties_api/std_bounties/management/commands/bounties_subscriber.py
- bounties_api/std_bounties/views.py
- bounties_api/user/management/commands/script_create_initial_users.py
- bounties_api/user/serializers.py
- bounties_api/utils/functional_tools.py
> PEP8 ALL THE THINGS

- bounties_api/std_bounties/views.py
> check if bounty id can be properly cast to int

- bounties_api/std_bounties/views.py
> Fix int of none

- bounties_api/std_bounties/views.py
> Fix fulfillments endpoint

- bounties_api/std_bounties/views.py
> Fix fulfillments endpoint again

- bounties_api/user/backend.py
@c-o-l-o-r @codeluggage  this one was bad :/
> Create use if does not exist

- bounties_api/notifications/email.py
The calculation was not showing correctly in the top part of the email
> Show contributed amount in email

- contract_subscriber/index.js
This is an old branch with a stab at ignoring specific `Invalid JSON RPC response` errors
@villanuevawill
> Ignore empty rpc infura error

- bounties_api/std_bounties/management/commands/bounties_subscriber.py
@villanuevawill @codeluggage it looks like it was just a typo in an if statement! 😄
> fix issue where fulfillment id came through to notification link as None

- bounties_api/bounties/settings.py
- bounties_api/bounties/tests.py
> Remove colorado, consensys and add pollenbees (removing bees) :)

- sql_jobs/hourly/category_ranks_pollenbees.sql
> New pollenbees to replace bees

- bounties_api/std_bounties/management/commands/initiate_bounty_cache.py
- bounties_api/std_bounties/seo_client.py
1. Initiation script for prerender
2. Blocks screenshotting for rinkeby bounties that are not in the platform list
> Initiation script and block screenshot for non-platform rink

- bounties_api/notifications/notification_templates.py
@villanuevawill @c-o-l-o-r tiny typo fix.
> Fix comment notification typo

- bounties_api/std_bounties/client_helpers.py
@villanuevawill @c-o-l-o-r 
Fixes https://rollbar.com/villanuevawill/Bounties/items/1220
EDIT: We probably want to do this some other way, but it was a good hotfix for the moment.
> Always fetch first known token of a type

- bounties_api/notifications/email.py
- bounties_api/notifications/notification_client.py
- bounties_api/notifications/notification_helpers.py
- bounties_api/notifications/templates/receivedRating.html
Trello: https://trello.com/c/UjEamQKw
Explorer PR: https://github.com/Bounties-Network/Explorer/pull/209
This changes the email link to the profile, and opens the reviews modal with a querystring.
> Change rating email link to open review modal on profile

- bounties_api/user/management/commands/resize_large_profile_images.py
> Fix resize script

- README.md
To new transition endpoints, new.api and newrinkeby api
> Readme endpoints 

- bounties_api/bounties/settings.py
- sql_jobs/hourly/category_ranks.sql
- sql_jobs/hourly/category_ranks_prague.sql
> Add prague network

- bounties_api/std_bounties/management/commands/get_token_values.py
- If it's not in CoinMarketCap cache, fetch the token data
> Handle manually added entries

- bounties_api/std_bounties/seo_client.py
Sitemap genreation for the main explorer uses SF and Prague as well
> Prague, SF used in sitemap generation for the main explorer

- bounties_api/requirements.txt
- bounties_api/user/auth_urls.py
- bounties_api/user/backend.py
- bounties_api/user/middleware.py
- bounties_api/user/views.py
> JWT support included

- bounties_api/std_bounties/management/commands/bounties_subscriber.py
> Argument that will just call the blacklist resolve

- bounties_api/std_bounties/views.py
@villanuevawill @codeluggage this adds ordering abilities to the reviews endpoint
> Allow review endpoint to be ordered

- logging/local.sh
> Add hour directory for logs

- bounties_api/analytics/urls.py
- bounties_api/analytics/views.py
> Add analytics endpoint to be used to determine a page view

- contract_subscriber/index.js
- Move error logic above int he subscriber process
> Move error logic in subscriber process

- bounties_api/user/views.py
@villanuevawill this resolves the issue @b-mueller brought to our attention here: https://github.com/Bounties-Network/Explorer/issues/288. The calculation will now divide the number of bounties which has payed out to at least one fulfiller by the total number of bounties with at least one fulfillment.
> Update issuer fulfillment acceptance rate calculation on user model

- bounties_api/bounties/settings.py
- contract_subscriber/constants.js
> update infura endpoint to v3
